### ISSUE TITLE
Error ready QRCODE

### ISSUE THREAD

**Issue by leoteixeira2016** [pranavms13/whatsapp-node-api#16]
(node:5304) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at __puppeteer_evaluation_script__:5:51
    at ExecutionContext._evaluateInternal (C:\API03\whatsapp-node-api-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\API03\whatsapp-node-api-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async Client.initialize (C:\API03\whatsapp-node-api-master\node_modules\whatsapp-web.js\src\Client.js:145:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5304) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pranavms13** [comment]
need more details.
when does this happen?

**Comment by kpbird** [comment]
@pranavms13  It happens to me as well. I am using OSX 11.1 with node v12.13.0

**Comment by lucassilvaesmeraldino** [comment]
the same problem here.

**Comment by mbeghe** [comment]
Same error. Trying to get **/auth/getqr**

**Comment by dhyeythumar** [comment]
I think this might also happen when someone deletes the token from WhatsApp.
I have also observed that even if you have the valid token WhatsApp web won't authenticate & keeps looping on the QR code scan page.  I this case you have to delete the older tokens & again scan the QR code.
