### ISSUE TITLE
Error: connect ECONNREFUSED 198.15.106.227:80   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) 

### ISSUE THREAD

**Issue by meosanjeev** [pranavms13/whatsapp-node-api#22]
HELLO got this error suddenly when everything works properly . and then node js app restart automatically please help me i dont want to restart my app help me to solve this problem : 

Error: connect ECONNREFUSED 198.15.106.227:80
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '198.15.106.227',
  port: 80
 }

**Comment by pranavms13** [comment]
need more details.
when does this happen ?

**Comment by meosanjeev** [comment]
currently its showing me when i am using multiuser for 4-5 days 
**timeouterror: timed out after 30000 ms while trying to connect to the browser! only chrome at revision r818858 is guaranteed to work**

**Comment by pranavms13** [comment]
run npm update and try again
should work

**Comment by meosanjeev** [comment]
its showing me 

2021-02-18T22:27:03:     at listOnTimeout (internal/timers.js:554:17)
2021-02-18T22:27:03:     at processTimers (internal/timers.js:497:7)
2021-02-18T22:47:02: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r818858 is guaranteed to work.
2021-02-18T22:47:02:     at Timeout.onTimeout (/var/www/html/wts_shared/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:204:20)

**Comment by 0xT01** [comment]
Same my problem.
try :
npm i whatsapp-web.js@v1.12.5

work for me.😊

**Comment by dhyeythumar** [comment]
You can check that happens in the browser by changing the headless to false

Here:
https://github.com/pranavms13/whatsapp-node-api/blob/f60e242a552b428f1739fb031e2ccf86782089f8/api.js#L17-L26

_I think its looping on the scan QR code page._

**Comment by meosanjeev** [comment]
thx for help
