### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by KatiaSishost** [pranavms13/whatsapp-node-api#26]
(node:1080) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at __puppeteer_evaluation_script__:5:51
    at ExecutionContext._evaluateInternal (D:\Usuario\Desktop\whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (D:\Usuario\Desktop\whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async Client.initialize (D:\Usuario\Desktop\whatsapp\node_modules\whatsapp-web.js\src\Client.js:145:9)
(node:1080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.

**Comment by pranavms13** [comment]
This happens with old version of WhatsApp Client 
More info here : https://github.com/pedroslopez/whatsapp-web.js/issues/564

Run ``npm update`` and then run it
