### ISSUE TITLE
Failed to Start api.js

### ISSUE THREAD

**Issue by semplon** [pranavms13/whatsapp-node-api#33]
Hi, this happen when i try to start api.js

/whatsapp-node-api/node_modules/node-webpmux/webp.js:424
    if (!this.data.extended) { this.#convertToExtended(); }
                                    ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/semplon/waapi/whatsapp-node-api/node_modules/whatsapp-web.js/src/util/Util.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by 0xT01** [comment]
Try :

`npm i whatsapp-web.js@v1.12.5`

**Comment by pranavms13** [comment]
Not sure what is happening here. Please clone latest code, reinstall npm modules and try again
