### ISSUE TITLE
Post Send Message Crash

### ISSUE THREAD

**Issue by achalag1** [pranavms13/whatsapp-node-api#52]
GET : /auth/checkclientstatus/61b0428a7d73d80bba8c248c
POST : /chatting/sendmessage
/sendmessage =>61b0428a7d73d80bba8c248c
/var/www/html/WhatsappCode/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'sendSeen')
    at __puppeteer_evaluation_script__:6:31
    at ExecutionContext._evaluateInternal (/var/www/html/WhatsappCode/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/var/www/html/WhatsappCode/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.sendMessage (/var/www/html/WhatsappCode/node_modules/whatsapp-web.js/src/Client.js:560:28)

**Comment by pranavms13** [comment]
It seems to be working fine. Please run npm update once more and try it.
