### ISSUE TITLE
 All Qr Code Gets Disconnected

### ISSUE THREAD

**Issue by achalag1** [pranavms13/whatsapp-node-api#53]
GET : /auth/getqr/60f17e36fc6f05a3f23085bc
GET : /auth/closeClient/612894c27cc9999f794c0098
/var/www/html/WhatsappCode/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:217
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /var/www/html/WhatsappCode/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (/var/www/html/WhatsappCode/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:216:16)
    at ExecutionContext._evaluateInternal (/var/www/html/WhatsappCode/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (/var/www/html/WhatsappCode/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:155:21)
    at WaitTask.rerun (/var/www/html/WhatsappCode/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:536:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
> whatsapp-node-api@0.0.3 start
> node api.js
Server Running Live on Port : 5000

**Comment by pranavms13** [comment]
Multiple clients aren't supported yet if that's what you are trying. Re open the issue with more details on how to reproduce this error
